# PostgreSQL / Neon
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=true

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1
quarkus.flyway.locations=db/migration

# JWT
smallrye.jwt.sign.key.location=jwt/privateKey.pem
mp.jwt.verify.publickey.location=jwt/publicKey.pem
mp.jwt.verify.issuer=chatify-jwt
 
# Cloudinary
app.cloudinary.url=${CLOUDINARY_URL}

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, PUT, POST, DELETE, OPTIONS
quarkus.http.cors.headers=Authorization, Content-Type

# Groq
quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.openai.api-key=${GROQ_API_KEY}
quarkus.langchain4j.openai.base-url=https://api.groq.com/openai/v1
quarkus.langchain4j.openai.chat-model.model-name=llama-3.3-70b-versatile